#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_LGE_SENSOR_GP2AP)	+= gp2ap002.o
obj-$(CONFIG_LGE_SENSOR_KR3DH)	+= kr3dh.o
obj-$(CONFIG_LGE_SENSOR_AK8973)	+= akm8973.o
